---

- name: Check if Virtualmin is already installed
  ansible.builtin.stat:
    path: '{{ virtualmin_bin_location }}'
  register: virtualmininstalled

- name: Download Virtualmin installation script
  ansible.builtin.get_url:
    url: '{{ virtualmin_download_url }}'
    dest: '{{ virtualmin_download_dest }}'
    mode: 0755
    owner: root
    group: root
  when: 'not virtualmininstalled.stat.exists'

- name: Install Virtualmin (LAMP bundle)
  ansible.builtin.command: '{{ virtualmin_download_dest }} --hostname {{ virtualmin_fqdn }} --force --bundle {{ virtualmin_bundle }}' 
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  changed_when: "'SUCCESS' in command_result.stdout"
  when: 'not virtualmininstalled.stat.exists and "LAMP" in virtualmin_bundle'

- name: Install Virtualmin (LEMP bundle)
  ansible.builtin.command: '{{ virtualmin_download_dest }} --hostname {{ virtualmin_fqdn }} --force --bundle {{ virtualmin_bundle }}'
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"
  changed_when: "'SUCCESS' in command_result.stdout"
  when: 'not virtualmininstalled.stat.exists and "LEMP" in virtualmin_bundle'

- name: Debug Output
  ansible.builtin.debug:
    msg: 'You can now login at the following address using user root and its respective password: https://{{ virtualmin_fqdn }}:10000'
  when: 'not virtualmininstalled.stat.exists'
