---

- name: Check if Virtualmin is already installed
  ansible.builtin.stat:
    path: '{{ virtualmin_bin_location }}'
  register: virtualmininstalled

- name: Download Virtualmin installation script
  ansible.builtin.get_url:
    url: '{{ virtualmin_download_url }}'
    dest: '{{ virtualmin_download_dest }}'
    mode: 0755
    owner: root
    group: root
  changed_when: not virtualmininstalled.stat.exists

- name: Install Virtualmin (LAMP bundle)
  ansible.builtin.command: '{{ virtualmin_download_dest }} --hostname {{ ansible_host }} --force --bundle {{ virtualmin_bundle }}'
  changed_when: not virtualmininstalled.stat.exists and virtualmin_bundle == "LAMP"

- name: Install Virtualmin (LEMP bundle)
  ansible.builtin.command: '{{ virtualmin_download_dest }} --hostname {{ ansible_host }} --force --bundle {{ virtualmin_bundle }}'
  changed_when: not virtualmininstalled.stat.exists and virtualmin_bundle == "LEMP"

- name: Debug Output
  ansible.builtin.debug:
    msg: 'You can now login at the following address using user root and its respective password: https://{{ ansible_facts.default_ipv4.address }}:10000'
  changed_when: not virtualmininstalled.stat.exists
